version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node:latest@sha256:436846910aacbdd81250add747a4be3346e24a460b774c3514025e29f05f0a2f

    ports:
      - 8000:8000
      - 8001:8001
      - 8020:8020
    links:
      - ipfs
      - postgres
      - ganache
    environment:
      postgres_host: postgres:5432
      postgres_user: postgres
      postgres_pass: 'letmein'
      postgres_db: postgres
      ipfs: ipfs:5001
      ethereum: development:http://ganache:8545

  ipfs:
    image: ipfs/go-ipfs
    ports:
      - 5001:5001

  postgres:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: 'letmein'

  ganache:
    image: daostack/migration:0.0.1-rc.7-v2
    ports:
      - 8545:8545
